GET https://api-dev.domecompass.com/groups?status=all-groups
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxIiwic3ViIjoyMDIsImF1ZCI6IioiLCJ0eXBlIjoidXNlciIsImlhdCI6MTYyOTE3NjA1NywibmJmIjoxNjI5MTc2MDU3LCJleHAiOjE2Mjk0MzUyNTd9.rmavZfANlLxvWyP_bVrHZNqm66mT-CgTKTs2p0nEkIw